### ISSUE TITLE
Generated type as 'Property' in yaml

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#14]
Issues in generated yaml from schema.json file

* Why are certain attributes with type as **string** generated as **property**?

For instance 'description' and 'dataProvider' below:

```

        "dataProvider": {
          "type": "string",
          "description": "Property. A sequence of characters identifying the provider of the harmonised data entity."
        },
        "description": {
          "type": "string",
          "description": "Property. A description of this item"
        },
```

are generated as:
```
    dataProvider:
      description: 'A sequence of characters identifying the provider of the harmonised data entity.'
      type: Property
    description:
      description: 'A description of this item'
      type: Property
```

* Why are certain attributes with type as **array** generated as **Property**?

For instance category below:

```
	"category": {
	    "type": "array",
	    "description": "Property. Model:'https://schema.org/Text'. Category of this point of interest. Allowed values: Those defined by the [Factual taxonomy](https://github.com/Factual/places/blob/master/categories/factual_taxonomy.json) together with the extended categories described by the specification. For instance the value `113` corresponds to beaches, and the value `311` corresponds to museums.",
	    "items": {
		"type": "string"
	    },
	    "minItems": 1
	},
```

are generated as:
```
   category:
      description: 'Category of this point of interest. Allowed values: Those defined by the [Factual taxonomy](https://github.com/Factual/places/blob/master/categories/factual_taxonomy.json) together with the extended categories described by the specification. For instance the value `113` corresponds to beaches, and the value `311` corresponds to museums.'
      items:
        type: string
      minItems: 1
      type: Property
      x-ngsi:
        model: https://schema.org/Text
```
