### ISSUE TITLE
Incorrect Description for postOfficeBoxNumber and postalCode

### ISSUE THREAD

**Issue by dpatil-fw** [smart-data-models/dataModel.PointOfInterest#9]
In the following model.yaml files:

https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Store/model.yaml
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Beach/model.yaml
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/PointOfInterest/model.yaml
https://github.com/smart-data-models/dataModel.PointOfInterest/blob/master/Museum/model.yaml

Under properties -> address - "_For example, Spain_" is incorrect in description of postOfficeBoxNumber and postalCode.

 ```
 postOfficeBoxNumber:
          description: 'Property. The post office box number for PO box addresses. **For example, Spain.** Model:''https://schema.org/postOfficeBoxNumber'''
          type: string
  postalCode:
          description: 'Property. The postal code. **For example, Spain**. Model:''https://schema.org/https://schema.org/postalCode'''
          type: string
```
